import type { Campaign, CampaignNode } from './types';

export const seedCampaigns: Campaign[] = [
  {
    id: 'jim-beam',
    brand: 'Jim Beam x US Soccer',
    concept: '"Home Field Advantage" — a cinematic film following a superfan\'s journey from a Kentucky backyard to the national stadium, where roots and the global game converge.',
    nodes: [
      {
        id: 'jb-hero',
        type: 'hero',
        title: 'Home Field Advantage',
        platform: 'Broadcast + YouTube',
        format: ':60 Cinematic Film',
        duration: '60 sec',
        description: 'Hero film following superfan\'s journey from backyard to stadium. Directed by Coming of Age. Kentucky roots meets global game.',
        ring: 1,
      },
      {
        id: 'jb-1',
        type: 'satellite',
        title: 'Backyard Sessions',
        platform: 'Instagram',
        format: ':30 Reels',
        duration: '4 × :30',
        description: 'Fan culture content shot at backyard watch parties. Authentic, lo-fi energy that mirrors the hero film\'s emotional core.',
        ring: 1,
      },
      {
        id: 'jb-2',
        type: 'satellite',
        title: 'Kentucky to the Pitch',
        platform: 'YouTube',
        format: 'Long-form',
        duration: '8 min',
        description: 'Extended director\'s cut showing the full superfan journey. Behind-the-scenes access and outtakes from the shoot.',
        ring: 1,
      },
      {
        id: 'jb-3',
        type: 'satellite',
        title: 'Superfan Cut',
        platform: 'TikTok',
        format: ':15 Series',
        duration: '6 × :15',
        description: 'Six-part TikTok series cutting into the most electric moments. Built for native TikTok discovery and shareability.',
        ring: 2,
      },
      {
        id: 'jb-4',
        type: 'satellite',
        title: 'Stadium Activation',
        platform: 'Live Event',
        format: 'Physical Activation',
        duration: '1 Match Day',
        description: 'Branded experience at a US Soccer home game. Jim Beam bar, fan photo moments, and live campaign integration.',
        ring: 2,
      },
      {
        id: 'jb-5',
        type: 'satellite',
        title: 'Home Field Podcast',
        platform: 'Spotify + Apple Podcasts',
        format: 'Audio Spot',
        duration: '45 min episode',
        description: 'Podcast takeover with the campaign director and superfan. Distributed across major audio platforms during the tournament.',
        ring: 2,
      },
    ],
  },
  {
    id: 'circle-arc',
    brand: 'Circle x Arc',
    concept: '"Bored Room" — a 12-hour livestream inside a corporate boardroom as five characters discover Arc changes everything about how they work. Comedy meets crypto infrastructure.',
    nodes: [
      {
        id: 'ca-hero',
        type: 'hero',
        title: 'Bored Room',
        platform: 'YouTube + Twitch',
        format: 'Livestream',
        duration: '12 hours',
        description: 'Five characters trapped in a boardroom discover Arc browser. Real-time comedy unfolding over a full workday, with crypto infrastructure as the punchline.',
        ring: 1,
      },
      {
        id: 'ca-1',
        type: 'satellite',
        title: 'Boardroom Clips',
        platform: 'TikTok',
        format: ':60 Highlights',
        duration: '8 clips',
        description: 'Best moments clipped from the live stream. Each clip functions as a standalone comedy piece that also drives discovery of the full event.',
        ring: 1,
      },
      {
        id: 'ca-2',
        type: 'satellite',
        title: 'Meet the Cast',
        platform: 'Instagram',
        format: 'Character Profiles',
        duration: '5 posts',
        description: 'Pre-launch character introduction series on Instagram. Each archetype — the CTO, the intern, the skeptic — gets a standalone post.',
        ring: 1,
      },
      {
        id: 'ca-3',
        type: 'satellite',
        title: 'Arc Demo Day',
        platform: 'YouTube',
        format: ':90 Feature',
        duration: '90 sec',
        description: 'Clean product demonstration using moments captured during the livestream. Shows Arc features in authentic, unscripted context.',
        ring: 2,
      },
      {
        id: 'ca-4',
        type: 'satellite',
        title: 'The Debrief',
        platform: 'Spotify + Apple Podcasts',
        format: 'Podcast Episode',
        duration: '60 min',
        description: 'Post-event debrief with the cast and Arc team. Covers what happened, what was real, and what the campaign says about browser-native work.',
        ring: 2,
      },
    ],
  },
  {
    id: 'purina',
    brand: 'Purina Pro Plan',
    concept: '"Fueled By" — a cinematic hero film following tennis champion Danielle Collins and her dog Quincy, showing how elite performance is fueled by the bond between athlete and animal.',
    nodes: [
      {
        id: 'pp-hero',
        type: 'hero',
        title: 'Fueled By',
        platform: 'Broadcast + YouTube',
        format: ':90 + :60',
        duration: ':90 broadcast / :60 YouTube',
        description: 'Cinematic hero film following Danielle Collins and Quincy through training, competition, and the quiet moments between. Directed for broadcast and long-form digital.',
        ring: 1,
      },
      {
        id: 'pp-1',
        type: 'satellite',
        title: 'Training Day BTS',
        platform: 'Instagram',
        format: ':15 Reels',
        duration: ':15',
        description: 'Behind-the-scenes content from the shoot. Shows the real relationship between Danielle and Quincy, capturing raw moments cut from the hero film.',
        ring: 1,
      },
      {
        id: 'pp-2',
        type: 'satellite',
        title: 'Danielle x Quincy',
        platform: 'Instagram',
        format: ':30 Lifestyle',
        duration: ':30',
        description: 'Lifestyle-format cut exploring the bond off the court. Softer, more emotional than the hero — built for Instagram feed performance.',
        ring: 1,
      },
      {
        id: 'pp-3',
        type: 'satellite',
        title: 'Athlete x Dog',
        platform: 'TikTok',
        format: ':30 Series',
        duration: '6 × :30',
        description: 'Six-episode TikTok series following the athlete-dog bond. Each episode explores a different theme: recovery, focus, joy, loyalty, fuel, performance.',
        ring: 2,
      },
      {
        id: 'pp-4',
        type: 'satellite',
        title: 'Product Launch',
        platform: 'Live Event',
        format: 'Pop-Up Activation',
        duration: '2-Day Event',
        description: 'NYC pop-up launch event celebrating the campaign. Interactive demos, Danielle appearance, and Pro Plan sampling for pet owners.',
        ring: 2,
      },
      {
        id: 'pp-5',
        type: 'satellite',
        title: 'Behind the Craft',
        platform: 'YouTube',
        format: 'Long-form',
        duration: '12 min',
        description: 'Director\'s commentary and making-of documentary. Explores how the cinematic language was developed to match the emotional truth of the bond.',
        ring: 2,
      },
    ],
  },
];

let nodeIdCounter = 1000;

export function generateFromConcept(brand: string, concept: string): Campaign {
  const id = `custom-${Date.now()}`;
  const mk = () => `gen-${nodeIdCounter++}`;

  return {
    id,
    brand,
    concept,
    nodes: [
      {
        id: mk(),
        type: 'hero',
        title: 'Hero Film',
        platform: 'Broadcast + YouTube',
        format: ':60 Cinematic',
        duration: '60 sec',
        description: `Hero campaign film for ${brand}. ${concept}`,
        ring: 1,
      },
      {
        id: mk(),
        type: 'satellite',
        title: 'Social Cut',
        platform: 'Instagram',
        format: ':15 Reels',
        duration: ':15',
        description: `Short-form cut optimised for Instagram discovery and shareability.`,
        ring: 1,
      },
      {
        id: mk(),
        type: 'satellite',
        title: 'Behind the Scenes',
        platform: 'YouTube',
        format: 'Long-form BTS',
        duration: '6 min',
        description: `Behind-the-scenes documentary exploring the making of the hero film.`,
        ring: 1,
      },
      {
        id: mk(),
        type: 'satellite',
        title: 'Social Series',
        platform: 'TikTok',
        format: ':30 Series',
        duration: '4 × :30',
        description: `Four-part TikTok series extending the campaign narrative in platform-native format.`,
        ring: 2,
      },
      {
        id: mk(),
        type: 'satellite',
        title: 'Live Activation',
        platform: 'Live Event',
        format: 'Activation',
        duration: '1 Day',
        description: `Brand activation event bringing the campaign to life in physical space.`,
        ring: 2,
      },
      {
        id: mk(),
        type: 'satellite',
        title: 'Audio Spot',
        platform: 'Spotify + Apple Podcasts',
        format: 'Podcast Integration',
        duration: '30 sec spot',
        description: `Audio-first extension distributed across podcast and streaming platforms.`,
        ring: 2,
      },
    ],
  };
}
